version: '3'
services:
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    ports:
      - "7575:7575"
    volumes:
      - /opt/homarr/config:/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - TZ=Asia/Shanghai
    networks:
      - tigerkits-network

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-config:/etc/nginx/conf.d
      - /opt/homarr/www:/usr/share/nginx/html
    networks:
      - tigerkits-network

networks:
  tigerkits-network:
    driver: bridge